#
# FF4ML simple configuration file
#

# NSL-KDD
dataset:
  name: nsl-kdd

# Dataset labels and ids
labels:
  - label_category_background
  - label_category_dos
  - label_category_r2l
  #- label_category_u2r
  - label_category_probe

# Class distribution
#label_category_dos           9590
#label_category_probe          857
#label_category_r2l            157
#label_category_background       4
#label_category_u2r              1

# Root folders
folder_paths:
  root_path: '../data/nsl-kdd/dat_batches/'
  root_path_output: '../results/'

# Data paths
file_paths:
  mc_file: 'output-KDD_all_extended_10000fobs_14bsize_multiclass.csv'
  mcfold_file: 'output-KDD_all_extended_10000fobs_14bsize_multiclass_folds.csv'
  mcvars_file: 'output-KDD_all_extended_10000fobs_14bsize_multiclass_folds_selecvars.csv'

# Bayesian based hyper-parameter selection
hyper_bayesian:
  n_iter: 30
  n_jobs: 3
  cv: 5
  n_points: 8
  random_state: 0

# Model's configuration
models:
  svc:
    hyperparameters:
      C:
        - 0.1
        - 100
      gamma:
        - 0.125
        - 2
      kernel: 'rbf'

    general:
      random_state: 0
      verbose: false

  rf:
    parameters:
      n_estimators:
        - 500 # low value
        - 600 # high value
      max_features:
        - 2 # low value
        - 16 # high value
    general:
      random_state: 0
      n_jobs: 2
      verbose: false

  lr:
    random_state: 0
    penalty: 'none'
    multi_class: 'auto'
    solver: 'lbfgs'
    verbose: false
