#
# FF4ML simple configuration file
#

# UGR16

# Dataset labels and ids
labels:
  - background
  - dos
  - nerisbotnet
  - scan
  - sshscan
  - udpscan
  - spam

folder_paths:
  root_path: './data/'
  root_path_output: './results/'

file_paths:
  mc_file: 'ugr16_multiclass.csv'
  mcfold_file: 'ugr16_multiclass_folds.csv'
  mcvars_file: 'ugr16_multiclass_folds_selecvars.csv'

