#
# FF4ML simple configuration file
#

# UGR16
dataset:
  name: ugr16

# Dataset labels and ids
labels:
  - label_background
  - label_dos
  - label_nerisbotnet
  - label_scan
  - label_anomaly_sshscan
  - label_anomaly_udpscan
  - label_anomaly_spam

# Root folders
folder_paths:
  root_path: '../data/ugr16/dat_batches/'
  root_path_output: '../results/'

# Data paths
file_paths:
  mc_file: 'output-UGR16_all_extended_10000fobs_395082bsize_multiclass.csv'
  mcfold_file: 'output-UGR16_all_extended_10000fobs_395082bsize_multiclass_folds.csv'
  mcvars_file: 'output-UGR16_all_extended_10000fobs_395082bsize_multiclass_folds_selecvars.csv'

# Bayesian based hyper-parameter selection
hyper_bayesian:
  n_iter: 30
  n_jobs: 3
  cv: 5
  n_points: 8
  random_state: 0

# Model's configuration
models:
  svc:
    hyperparameters:
      C:
        - 0.1
        - 100
      gamma:
        - 0.125
        - 2
      kernel: 'rbf'

    general:
      random_state: 0
      verbose: false

  rf:
    parameters:
      n_estimators:
        - 500 # low value
        - 600 # high value
      max_features:
        - 2 # low value
        - 16 # high value
    general:
      random_state: 0
      n_jobs: 2
      verbose: false

  lr:
    random_state: 0
    penalty: 'none'
    multi_class: 'auto'
    solver: 'lbfgs'
    verbose: false
